git:
  depth: false

env:
  - HUGO_VERSION="0.49.2"
  - HUGO_VERSION="0.50"
  - HUGO_VERSION="0.51"
  - HUGO_VERSION="0.52"
  - HUGO_VERSION="0.53"
  - HUGO_VERSION="0.54.0"
  - HUGO_VERSION="0.55.0"
  - HUGO_VERSION="0.56.0"

install:
  - wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mv hugo ~/bin/
  - gem install html-proofer

script:
  - cd exampleSite
  - HUGO_THEME=hugo-theme-introduction hugo --themesDir ../.. -v
  - htmlproofer public --check-html --disable-external
