baseURL                          = "http://example.com/"  # Your domain name. Must end with "/"
theme                            = "introduction"
DefaultContentLanguage           = "en"                    # Default language for multilingual sites
# disqusshortname                 = ""                       # https://gohugo.io/content-management/comments
# googleAnalytics                 = ""                       # https://gohugo.io/templates/internal/#google-analytics

[params]
    themeStyle                   = "light"                 # Choose "light" or "dark"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = "youremail@email.com"   # E-mail address for contact section
    # customCSS                    = ["foo.css"]             # Include custom css files placed under assets/

    # Configure the home page
    [params.home]
        introHeight              = "large"                 # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects

        localTime                = true                    # Show your current local time in contact section
        timeZone                 = "America/Los_Angeles"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Staticman support
    # Input your API endpoint and info of your target GitHub/GitLab repo
    # ReCAPTCHA is optional.  If enabled, use your own site key and encrypted site secrets.
    # The site secret should be encrypted via https://{STATICMAN-API}/v3/encrypt/{SITE-SECRET}
    # [Params.staticman]
    # api = "https://staticman3.herokuapp.com/v3/entry/{GITLAB|GITHUB}/{USERNAME}/{REPO}/{BRANCH}/comments"
    # [Params.staticman.recaptcha]
    # sitekey = "6LeGeTgUAAAAAAqVrfTwox1kJQFdWl-mLzKasV0v"
    # secret = "hsGjWtWHR4HK4pT7cUsWTArJdZDxxE2pkdg/ArwCguqYQrhuubjj3RS9C5qa8xu4cx/Y9EwHwAMEeXPCZbLR9eW1K9LshissvNcYFfC/b8KKb4deH4V1+oqJEk/JcoK6jp6Rr2nZV4rjDP9M7nunC3WR5UGwMIYb8kKhur9pAic="

    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        facebook                 = true
        googlePlus               = true
        pinterest                = true

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://twitter.com/"
        icon  = "twitter" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://facebook.com/"
        icon  = "facebook-f" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://linkedin.com/"
        icon  = "linkedin-in" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url = "mailto:youremail@email.com"  # For a direct email link, use "mailto:test@example.org".
        icon = "paper-plane" # icon name without the 'fa-'
        icon_pack = "fas"


# If you don't want to use the default menu, you can define one by yourself
# [[menu.main]]
#     name    = "Home"
#     url     = "/"
#     weight  = 0
# [[menu.main]]
#     name    = "Blog"
#     url     = "/blog/"
#     weight  = 1

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 0
        title            = "Introduction"
        [languages.en.params]
            description  = "Website Description"   # Max 160 characters show in search results
            # footerText   = ""                      # Text to override default footer text (markdown allowed)

    [languages.es]
        languageName     = "Español"
        languageCode     = "es"
        contentDir       = "content/es"
        weight           = 1
        title            = "Introducción"
        [languages.es.params]
            description  = "Descripcion del sitio web"
            # footerText   = ""

    [languages.de]
        languageName     = "Deutsch"
        languageCode     = "de"
        contentDir       = "content/de"
        weight           = 2
        title            = "Vorstellung"
        [languages.de.params]
            dateFormat   = "2. January 2006"
            description  = "Beschreibung der Webseite"
            # footerText   = ""
