baseurl             = "https://introduction.com/"   # Your domain name. Must end with "/"
languageCode        = "en-us"
title               = "Introduction"
theme               = "introduction"
enforce_ssl         = false
builddrafts         = false                         # Include pages with draft status of true
canonifyurls        = true                          # Turns relative urls into absolute urls
# disqusshortname   = "xxx"                         # Enable Disqus for comments
# googleAnalytics   = "xxx"

[params]
    bloghead        = "Blog"                        # Full name shows on blog post pages
    firstname       = "Introduction"                # First name shows in introduction on main page
    tagline         = "I'm a theme for Hugo."       # Appears after the introduction
    introheight     = "large"                       # Input either 'medium' or 'large' or 'fullheight'
    theme           = "dark"                        # Choose 'light' or 'dark'
    avatar          = "img/profile.jpg"             # Path to image in static folder eg. img/avatar.png, or comment out to remove
    email           = "youremail@email.com"         # Shows in contact section, or leave blank to omit
    localtime       = true                          # Show your current local time in contact section
    timezone        = "America/Los_Angeles"         # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    dateform        = "Jan 2, 2006"
    dateformfull    = "Mon Jan 2 2006 15:04:05 EST"
    cachebuster     = true                          # Add the current unix timestamp in query string for cache busting css assets
    description     = "Website Description"         # Max 160 characters show in search results
    faviconfile     = "img/fav.ico"
    highlightjs     = true                          # Syntax highlighting
    footertext      = ""                            # Text to show in footer (overrides default text)
    fadein          = true                          # Turn on/off the fade-in effect

    showblog            = true                      # Show Blog section on home page
    showprojects        = true                      # Show Projects section on home page
    placeholderimg      = "/img/workday.jpg"        # For Projects without image
    showallposts        = false                     # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
    showlatest          = true                      # Show latest blog post summary
    sharebuttons        = true                      # On post pages, show share this social buttons

    # Share buttons
    sharetwitter        = true
    sharefacebook       = true
    sharepinterest      = false
    sharegoogleplus     = true

# Social icons appear in introduction and contact section. Add as many more as you like.
# Find icon names here: http://fontawesome.io/cheatsheet/

[[params.social]]
    url = "https://twitter.com/"
    icon = "twitter"

[[params.social]]
    url = "https://facebook.com/"
    icon = "facebook"

[[params.social]]
    url = "https://linkedin.com/"
    icon = "linkedin"